<div class="column-one-fourth sidebar">


    <!-- Categories -->

    <div class="sidebar-widget categories">
        <!-- Title -->
        <h3>Категории новостей</h3>
        <!-- Category Links -->
        <?foreach ($this->categories as $category) :?>
            <a href="/news/<?= $category['cat_code']; ?>"><?= $category['cat_name']; ?></a>
        <? endforeach; ?>
    </div>

    <!-- END Categories -->



    <!-- Search -->

    <div class="sidebar-widget search">
        <!-- Title -->
        <h3>Поиск по сайту</h3>
        <!-- Search Form -->
        <form name="blog-search" method="get" action="/search/">
            <div class="container">
                <!-- Textbox -->
                <input type="text" id="blog-search" name="blog-search" placeholder="Искать">
                <!-- Search Button -->
                <input type="submit" id="go" class="go" value="&#xf002;">
            </div>
        </form>
    </div>

    <!-- END Search -->



    <!-- Latest Project -->

    <div class="sidebar-widget project">
        <!-- Title -->
        <h3>Новость дня</h3>
        <!-- Image -->
        <a href="#" class="image-link"><img alt="" src="\public\images\placeholders\preview4.jpg" class="fullwidth"></a>
        <!-- Project Title -->
        <h3 class="sub-title"><a href="#">Заголовок новости</a></h3>
        <!-- Tags -->
        <div class="tags">Категория</div>
    </div>

    <!-- END Latest Project -->



    <!-- Popular Posts -->

    <div class="sidebar-widget posts">
        <!-- Title -->
        <h3>Последнее</h3>


        <!-- Post -->

        <div class="post">
            <!-- Image Column -->
            <div class="img-column">
                <a href="blog-post.html" class="image-link mini"><img alt="" src="\public\images\placeholders\preview9-mini.jpg" class="fullwidth"></a>
            </div>
            <!-- Content Column -->
            <div class="content-column">
                <!-- Post Title -->
                <h3 class="sub-title"><a href="blog-post.html">Взаимодействие корпорации и клиента экономит баинг и селлинг.</a></h3>
                <!-- Date -->
                <div class="date">31 августа 2016</div>
            </div>
        </div>

        <!-- END Post -->



        <!-- Post -->

        <div class="post">
            <!-- Image Column -->
            <div class="img-column">
                <a href="blog-post.html" class="image-link mini"><img alt="" src="\public\images\placeholders\preview11-mini.jpg" class="fullwidth"></a>
            </div>
            <!-- Content Column -->
            <div class="content-column">
                <!-- Post Title -->
                <h3 class="sub-title"><a href="blog-post.html">Взаимодействие корпорации и клиента экономит баинг и селлинг.</a></h3>
                <!-- Date -->
                <div class="date">31 августа 2016</div>
            </div>
        </div>

        <!-- END Post -->



        <!-- Post -->

        <div class="post">
            <!-- Image Column -->
            <div class="img-column">
                <a href="blog-post.html" class="image-link mini"><img alt="" src="\public\images\placeholders\preview8-mini.jpg" class="fullwidth"></a>
            </div>
            <!-- Content Column -->
            <div class="content-column">
                <!-- Post Title -->
                <h3 class="sub-title"><a href="blog-post.html">Взаимодействие корпорации и клиента экономит баинг и селлинг.</a></h3>
                <!-- Date -->
                <div class="date">31 августа 2016</div>
            </div>
        </div>

        <!-- END Post -->


    </div>

    <!-- END Popular Posts -->


</div>